import HandoffPreview from "./HandoffPreview";
import OnboardingLearningPlan from "./OnboardingLearningPlan";

function confirmDelete(onDelete, id) {
  if (window.confirm("이 인수인계 문서를 삭제할까요?")) onDelete(id);
}

function ArchiveHeader({ selected, onList, onboarding }) {
  return <><header className="hc-page-head"><button className="hc-icon-btn" type="button" onClick={onList} title="문서함으로"><i className="ti ti-arrow-left" /></button><div><span>{onboarding ? "SAVED ONBOARDING PLAN" : "SAVED TRANSFER PLAN"}</span><h1>{onboarding ? "저장된 신입 온보딩 플랜" : "저장된 업무 인수인계"}</h1></div></header><div className="hc-archive-meta"><span className="hc-status">초안</span><span><i className="ti ti-calendar" />{new Date(selected.createdAt).toLocaleString("ko-KR")}</span><span><i className="ti ti-user" />{selected.createdBy}</span></div></>;
}

export default function HandoffArchive({ archives, filter, selected, onFilter, onOpen, onBack, onList, onClone, onPreviewChange, onDelete }) {
  if (selected?.type === "onboarding") return <main className="hc-archive hc-onboarding-archive"><ArchiveHeader selected={selected} onList={onList} onboarding /><OnboardingLearningPlan previewData={selected.previewData} candidates={selected.selectedCandidates || []} selectedIds={selected.selectedIds || []} conditions={{ ...(selected.conditions || {}), target: "신입", department: selected.department || selected.conditions?.department || "확인 필요" }} archived /><footer className="hc-archive-actions"><button type="button" className="hc-delete-btn" onClick={() => confirmDelete(onDelete, selected.id)}><i className="ti ti-trash" />삭제</button><button type="button" onClick={() => onClone(selected)}><i className="ti ti-copy" />복제해서 새로 만들기</button></footer></main>;

  if (selected) return <main className="hc-archive hc-handoff-archive"><ArchiveHeader selected={selected} onList={onList} /><HandoffPreview previewData={selected.previewData} archived onPreviewChange={(previewData) => onPreviewChange(selected.id, previewData)} /><footer className="hc-archive-actions"><button type="button" className="hc-delete-btn" onClick={() => confirmDelete(onDelete, selected.id)}><i className="ti ti-trash" />삭제</button><button type="button" onClick={() => onClone(selected)}><i className="ti ti-copy" />복제해서 새로 만들기</button></footer></main>;

  const visible = archives.filter((item) => filter === "all" || item.type === filter);
  return <main className="hc-archive"><header className="hc-page-head"><button className="hc-icon-btn" type="button" onClick={onBack} title="처음으로"><i className="ti ti-arrow-left" /></button><div><span>SAVED DOCUMENTS</span><h1>인수인계 문서함</h1></div></header><div className="hc-archive-toolbar"><div>{[["all", "전체"], ["handoff", "업무 인수인계"], ["onboarding", "신입 온보딩"]].map(([value, label]) => <button type="button" className={filter === value ? "active" : ""} onClick={() => onFilter(value)} key={value}>{label}</button>)}</div><span>{visible.length}건</span></div>{visible.length ? <section className="hc-archive-list">{visible.map((item) => <div className="hc-archive-card-wrap" key={item.id}><button type="button" className="hc-archive-card" onClick={() => onOpen(item.id)}><span className="hc-archive-kind">{item.type === "onboarding" ? "신입 온보딩" : "업무 인수인계"} · 초안</span><h2>{item.title}</h2><p>{item.owner || item.target} {item.receiver ? `→ ${item.receiver}` : ""} · {item.department}</p><p>{item.customer || "전체 고객사"} · {item.scope || "온보딩 가이드"}</p><footer><span>{item.createdBy} · {new Date(item.createdAt).toLocaleDateString("ko-KR")}</span><i className="ti ti-chevron-right" /></footer></button><button type="button" className="hc-archive-card-delete" title="삭제" onClick={(event) => { event.stopPropagation(); confirmDelete(onDelete, item.id); }}><i className="ti ti-trash" /></button></div>)}</section> : <section className="hc-empty"><i className="ti ti-archive" /><h2>저장된 문서가 없습니다</h2><p>결과 미리보기에서 초안을 저장하면 이 문서함에 표시됩니다.</p></section>}</main>;
}
